"""Image-generation backend Protocol. Implementations: api_gemini.py, api_fake.py."""

from typing import Protocol


class BackendError(Exception):
    """The backend failed to produce an image (HTTP error, refusal, bad response)."""


class ImageBackend(Protocol):
    name: str
    # Identity of the image-generation model, used for the per-project model
    # lock (a project must be generated by one model throughout).
    model_id: str

    def generate(self, refs: list[bytes], prompt: str) -> bytes:
        """Generate one PNG image from reference images and a prompt."""
        ...

    def critique(self, images: list[bytes], prompt: str) -> str:
        """Answer a text question about the given images (for `shot review`)."""
        ...
